server:
  port: 10086
spring:
  application:
    name: nas-user #指定服务名
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/novel_system?serverTimezone=GMT
    username: root
    password: 123456
